# Site settings
title:       Pixyll
email:       
author:      Chris Frei
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     "/pixyll"
url:         "http://4711.github.io"

# Google analytics
google_analytics: 

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: 4711
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

# Exclude these files
exclude:
 - "node_modules"
 - "package.json"
 - "README.md"
 - "Gemfile"
 - "gulpfile.js"

prose:
  rooturl: '_posts'
  siteurl: 'http://4711.github.io/pixyll/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
